### ISSUE TITLE
Swapping model does not rerender all children

### ISSUE THREAD

**Issue by dylanfoster** [runspired/smoke-and-mirrors#124] opened 2016-07-26 20:53 UTC
Scenario:

I have a model which is filtered based on whether I'm a manager or not. When toggling this setting, a new request is made with the filter like so:

`controller.js`

``` javascript
fetchData() {
  let promise;

  if (get(this, 'isMine')) {
    promise = this.store.query(type, { filter: { where: { id: manager.get('id') }}});
  } else {
    promise = this.store.query(type, { filter: { where: { id: { neq: manager.get('id') }}}});
  }

  return promise.then(data => {
    set(this, 'model', data);
  });
},
onIsMineChange: observer('mine', function () {
  return this.fetchData();
});
```

`template.hbs`

``` handlebars
{{#vertical-collection content=model as |foo|}}
  <li>foo.name</li>
{{/vertical-collection}}
```

The initial render is fine, but any time I toggle, it doesn't re render all the children. In this case, let's say it's 6 vs 3 records, initial render shows 6, first toggle shows 3, but toggle back shows 3. `vertical-collection` has all 6 records in both `content` and `children` and there are 6 `vertical-items` all with the necesary data, they're just not rendering their block content.

Inspecting the missing ones shows that `contentInserted` is false.

**Comment by runspired** [comment] 2016-09-28 23:22
@dylanfoster is this still an issue on `0.6.0` ? I didn't directly investigate it but I did make changes that simplified how it determines to rerender and should have helped.

**Comment by dylanfoster** [comment] 2016-09-30 00:14
@runspired I'll have to dig in and check it out with the latest release. I'll get back to you.

**Comment by scottmessinger** [comment] 2016-10-11 14:14
@runspired I'm trying out 0.6.1 smoke-and-mirrors in 2.9.0-beta.5 and I'm seeing the same issue.

**Comment by scottmessinger** [comment] 2016-10-14 16:41
After looking into it, it *appears* to be a mistake on my part. So, for now, it's working great!

**Comment by rafael-paiva** [comment] 2017-04-18 21:11
I'm still having the same issue on `0.6.2`. Any idea how to fix it?

**Comment by runspired** [comment] 2017-04-18 21:22
@rafael-paiva could you try the beta? https://github.com/html-next/vertical-collection

We extracted vertical-collection from smoke-and-mirrors, and once it reaches 1.0 we'll bump smoke-and-mirrors to use it as well.

**Comment by rafael-paiva** [comment] 2017-04-18 22:40
Thanks for you quick response @runspired, but I think we're going to hold on this for now. I'll update when I get back to this and find a solution.

Just to give a little more info, the issue is exactly what @dylanfoster described: the items are all there but the block content is not being rendered because `contentInserted` is false. If I set it manually to `true`, the content is properly shown.

**Comment by runspired** [comment] 2018-04-08 22:41
Should be fixed by updating to `@html-next/vertical-collection` (now re-exported by this lib)

**Closed by runspired** 2018-04-08 22:41 UTC
Labels: bug
