### ISSUE TITLE
Readme instructions for installation and usage?

### ISSUE THREAD

**Issue by andrewhavens** [runspired/smoke-and-mirrors#111] opened 2016-04-14 18:22 UTC
Hi Chris,

I'm getting started with Ember CLI, so I'm pretty new to this. I noticed that there aren't any installation or setup instructions in the readme, nor on the website. Do I just run `ember install smoke-and-mirrors`?

It would probably help newcomers (like me) if there was a basic intro on how to install and set up (import?) the package and its services/components.

Thanks!

**Comment by runspired** [comment] 2016-07-22 21:09
Closing as duplicate of #118

**Closed by runspired** 2016-07-22 21:09 UTC
